### ISSUE TITLE
Expand text richness on events

### ISSUE THREAD

**Issue by yangwao** [alii/linear-discord-serverless#4]
I really like your work and probably support this as well.

We are using it for our KodaDot discord and so far it's amazing.

I've found that missing fields like **who** updated the issue 
and whenever someone creates a comment on an issue, add some name of an issue to see a bit more context of "update" in the channel, so I don't need to click on it

I'm thinking to support this integration to keep it running:)

**Comment by alii** [comment]
I'm thinking of writing a v2 version of this since it will require an API token to fetch more information and the linear SDK.
