### ISSUE TITLE
Add more context to comment event 

### ISSUE THREAD

**Issue by yangwao** [alii/linear-discord-serverless#6]
Kira vs Kira2 (new one) 

In the new version, I would deduplicate information on comment, or that's because it's using my personal token?

Plus I would add context, i.e. which issue was commented, i.e. incl. starting 5-7 words from issue name to the message and identifier, in this case, **KOD-216** 
![image](https://user-images.githubusercontent.com/5887929/134812467-c5ac8ec5-ed9f-45bb-802d-efeb0f34d5d6.png)

Happy to test it, give feedback and use it long-term! :)

**Comment by alii** [comment]
Thanks for the feedback!
