### ISSUE TITLE
Feature request yo

### ISSUE THREAD

**Issue by SincerelyFaust** [alii/linear-discord-serverless#8]
Dear Alistair,

as a part of an open source project that is an avid fan and user of this wonderful service, I'd like to thank you for the great work you've done!
I have a few suggestions I'd like to share with you in case you're looking for some feedback!
Considering that each Linear issue holds valuable information, I think it would be neat to see the issue title and priority also displayed in the embed that is sent through the webhook.
In my opinion, you can display the priority in a field in the embed's body and the issue title in the embed title.
Hope you have a wonderful day! :)

Sincerely yours,
Marin.

**Comment by looskie** [comment]
love letter 💌😽

**Comment by alii** [comment]
wooo thank you for your kind words Marin, will work on these! 😃 

I recently added support for showing the issue title but you are right that I have missed priority this time around. I'll add priortity when I can, probably work on it this weekend 👍🏻
